### PR TITLE
Change TargetPlatformMinVersion to minimal possible

### PR DESCRIPTION
**Pull request by maxkatz6**
Hello. Thanks for great library!
In my application I use handwritten code with same functional for cases, when user want to attach visual tree to bug report, so it should works in runtime, not only for e2e-tests.
My application works on 15053+, but I don't see any reason to not target 10240.

### CODE REVIEW

**Comment by asklar** [comment]
@maxkatz6  thanks!

**Comment by maxkatz6** [comment]
@asklar hi!
Would you update nuget package to include these changes?

**Comment by asklar** [comment]
@maxkatz6 sure :) https://www.nuget.org/packages/XamlTreeDump/1.0.4

**Comment by maxkatz6** [comment]
@asklar thanks!

**Pull request merged**
